### ISSUE TITLE
ERROR: when unmarshalling JSON: Object 'Kind' is missing in 'null

### ISSUE THREAD

**Issue by drpaneas** [kubic-project/kubic-init#176]
Start the `kubic-init` service, and you will see this error. You can skip it (it will not affect the creation of the cluster) but it would be good to get rid of it:

```
journalctl -u kubic-init -f
[...]
manifests.go:108] [kubic] getting manifest from 'https://raw.githubusercontent.com/kubic-project/registries-operator/master/deployments/registries-        operator-full.yaml'
manifests.go:95] [kubic] ERROR: when unmarshalling JSON: Object 'Kind' is missing in 'null
```

**Comment by MalloZup** [comment]
It should be a warn instead of err

**Comment by slremy** [comment]
I am not sure if this is also your issue, but I saw ```error unmarshaling JSON: Object 'Kind' is missing in....MYJSON``` because I inadvertantly used a docker_compose yaml instead of a Kubernetes Deployment yaml
