### ISSUE TITLE
Replace version "1.13" doesn't match patterns

### ISSUE THREAD

**Issue by drpaneas** [kubic-project/kubic-init#177]
`systemctl start kubic-init` fails with the following:

```
Jan 22 16:14:42 d229 kubic-init[25343]: I0122 15:14:42.932413      23 initconfiguration.go:169] loading configuration from the given file
Jan 22 16:14:42 d229 kubic-init[25343]: version "1.13" doesn't match patterns for neither semantic version nor labels (stable, latest, ...)

This '1.13' gets created from kubeadm config on the fly:

1 common.go:106] [kubic]         kubernetesVersion: "1.13"
```

The fix should be: at the `./pkg/config/defaults.go`
```
-       DefaultKubernetesVersion = "1.13"
+       DefaultKubernetesVersion = "1.13.2"
```

**Comment by inercia** [comment]
@drpaneas the whole issue with the `hyperkube` image will not be fixed until we change the `kiwi` file and add the `v` to the version. Until then, I think I will revert the use of our hyperkube image...

**Comment by drpaneas** [comment]
I fixed that: https://github.com/kubic-project/kubic-init/pull/184 
the PR got merged a few seconds ago. In a few minutes this should be fixed already.
