### ISSUE TITLE
Cannot pull pause image

### ISSUE THREAD

**Issue by drpaneas** [kubic-project/kubic-init#180]
```
[ERROR ImagePull]: failed to pull image registry.opensuse.org/devel/kubic/containers/container/kubic/pause:3.1: output: time="2019-01-22T16:17:42Z" level=fatal msg="pulling image failed: rpc error: code = Unknown desc = Error reading manifest 3.1 in registry.opensuse.org/devel/kubic/containers/container/kubic/pause: manifest unknown"
```

This should be fixed by 
```
- registry.opensuse.org/devel/kubic/containers/container/kubic/pause:3.1
+ registry.opensuse.org/devel/kubic/containers/container/kubic/pause:0.1
```

However we have to check why there's such a big difference in the versions.

**Comment by nirmoy** [comment]
It's not possible to do that. we have to update https://build.opensuse.org/package/show/devel:CaaSP:Head:ControllerNode/kubernetes-node-image-pause to 3.1

**Comment by drpaneas** [comment]
I am looking into it. It has to be subpackage of kubernetes so it gets updated as well in normal basis.

**Comment by drpaneas** [comment]
Why did you close the issue?
