### ISSUE TITLE
Create a testing infrastructure

### ISSUE THREAD

**Issue by inercia** [kubic-project/kubic-init#56]
Our `kubic-init` container needs a testing infrastructure. This would include:

* On a first stage we would need some basic unit tests (ie, check we are generating the right `kubadm.yaml` from a given `kubic-init.yaml` file).
* Then we would need some integration tests that could spawn some VMs (probably using our Terraform files) and then perform some checks.

**Comment by MalloZup** [comment]
@inercia closing since we are doing it
