### ISSUE TITLE
Building from src code-generation fails

### ISSUE THREAD

**Issue by MalloZup** [kubic-project/kubic-init#60]
# description:
building from src with the makefile, failed in 2 points at moment.
1) the go.sum failed saying the checksum was outdated. ( by this error i just removed the file, then worked)
2) the deepcopy failed ( i have installed last one)
i have tried this out in 2 differents OS-Leap15 Computers

Using $GOPATH
~/go/src/github.com/kubic-project/kubic-init> 

# howto
when building from source with 
```
make
>>> Updating deepcopy files in pkg/config/
sh -c GO111MODULE=off deepcopy-gen -O zz_generated.deepcopy -i ./... -h ../../hack/boilerplate.go.txt
F1108 22:18:13.821865    6534 deepcopy.go:866] Hit an unsupported type invalid type.
pkg/config/config.go:18: running "sh": exit status 255
make: *** [Makefile:103: pkg/config/zz_generated.deepcopy.go] Error 1

go version go1.11.2 linux/amd64

```

As stated in desc, i was thinking i had an unstable env. but i tried it with a new Env on other Computer and i get now same error

**Comment by MalloZup** [comment]
how i fixed it:

go get -u k8s.io/apiserver, k8s.io/apimachinery, and k8s.io/client-go. 

( i dunno if we need to update the modules or update the doc)

**Comment by inercia** [comment]
You are right, `deepcopy-gen` will fail if some dependencies are not downloaded in advance.

Could you please try this and see if `k8s.io/apimachinery` is enough?

```
make clean-generated
rm -rf $GOPATH/src/k8s.io
make                               # this should FAIL
go get -u k8s.io/apimachinery
make                               # this should SUCCEED now
```

**Comment by MalloZup** [comment]
@inercia  yop that worked out.

I am searching now how to update the requirement
