### ISSUE TITLE
modulify terraform files

### ISSUE THREAD

**Issue by MalloZup** [kubic-project/kubic-init#71]
# Description:

I think we should try to make lower the cognitive load we have on the `main.tf` at moment.

I was thinking that we should have 2 modules or others for splitting up the main.tf in sub-resources.

My proposal would be to split : `seeder` and `other res` modules.

# Tasks/Research:

- [ ] create a module resource plan with team

- [ ] create PR 

I opened this card for gathering some feedback, it doesn't have to be adressed

**Comment by inercia** [comment]
I don't know if this would make things easier for removing the differences between `tf-full`/`tf-nodes`. If that is the case, +100.

**Comment by MalloZup** [comment]
@inercia i close this since we take care on the PR on wip
